### ISSUE TITLE
dockerhero-php-7.2-fpm

### ISSUE THREAD

**Issue by Casper-O** [johanvanhelden/dockerhero#20]
Hope you would also add a dockerhero image for php-7.2-fpm

**Comment by johanvanhelden** [comment]
Thank you for your suggestion - that is a great idea. I will put it on my todo list.

**Comment by johanvanhelden** [comment]
@Casper-O 

The PHP 7.2 image has been released. You can switch to it by adding a `docker-compose.override.yml` file with the following contents:

```
version: '2'

services:
  php:
    image: johanvanhelden/dockerhero-php-7.2-fpm:latest
```

In order to change back to 7.1, either change the image version number or delete the override file.
